# Training datasets for different folds
datasets:
    - ml/mt/fold0_mt_training_dataset.root
    - ml/mt/fold1_mt_training_dataset.root

# Base path for all output files
output_path: ml/mt

# Define classes based on tree names in dataset file
classes:
    - ggh
    - qqh
    - ztt
    - zll
    - w
    - tt
    - ss
    - misc

# Set class weights
class_weights:
    ggh: 203.6
    qqh: 2050.5
    ztt: 1.7
    zll: 17.4
    w: 7.1
    tt: 17.2
    ss: 7.1
    misc: 56.1

# Define global scale factor, which is multiplied to all event weights
global_weight_scale: 1.0

# Set event weight variable
event_weights: training_weight

# Define list of variables to be used for training
variables:
    - pt_1
    - pt_2
    - jpt_1
    - jpt_2
    - jphi_1
    - jphi_2
    - njets
    - nbtag
    - mt_1
    - mt_2
    - ptvis
    - pt_tt
    - mjj
    - m_vis
    - dijetpt
    - met

# Split of dataset in training and validation (in TMVA called training and testing)
train_test_split: 0.75

# Define preprocessing
preprocessing: standard_scaler

# Set random seed for initialization of parameters and dataset splits
seed: 1234

# Define the model parameter
model:
    name: smhtt_dropout
    batch_size: 1000
    epochs: 10000
    early_stopping: 20
    save_best_only: true
